#ifndef HTTPC_PROPERTIES
#define HTTPC_PROPERTIES

#define DEFAULT_PORT 8000
#define BUFFER_SIZE 1024 * 4
#define TIMEOUT_SECONDS 5
#define MAX_FORKS_NUMBER 1024 * 4

#define GET_MIME_TYPE 0
#define NON_BLOCKING 1
#define READ_INDEX_HTML 1

#endif